---
# Create databases on existing SQL instances
- hosts: sqlserver

  tasks:
    - name: Ensure "{{ db_name }}" is present on "{{ ansible_hostname }}"
      mssql_db:
        name: "{{ db_name }}"
        login_host: "{{ db_host }}"
        login_user: "{{ db_host_user }}"
        login_password: "{{ db_host_pwd }}"
        state: present
