---
# Deploy one ore more apps on Windows Hosts
- hosts: all
  # become: true
  # become_method: runas

  tasks:
    - name: Deploy applications on "{{ ansible_hostname }}"
      win_chocolatey:
        name: "{{ item }}"
        state: "{{ apps_state }}"
      with_items: "{{ apps }}"
