---
# Manage Groups in Active Directory
- hosts: dc
  # become: true
  # become_method: runas

  tasks:
    - name: Manage Active Directory group "{{ ad_group_name }}"
      win_domain_group:
         name: "{{ ad_group_name }}"
         scope: "{{ ad_group_scope }}"
         category: "{{ ad_group_category }}"
         organizational_unit: "{{ ad_group_ou }}"
         description: "{{ ad_group_des }}"
         state: present
