---
# Manage Users in Active Directory
- hosts: dc
  # become: true
  # become_method: runas
  vars:
    ad_username: ''
    ad_username}: ''
    ad_firstname: ''
    ad_surname: ''
    ad_company: ''
    ad_userpwd: ''
    ad_user_state: ''
    ad_groups: ''
    ad_street: ''
    ad_city: ''
    ad_state: ''
    ad_postal_code: ''
    ad_country: ''

  tasks:
    - name: Manage Active Directory user "{{ ad_username }}"
      win_domain_user:
         name: "{{ ad_username }}"
         upn: "{{ ad_username}}@testlab.local"
         firstname: "{{ ad_firstname }}"
         surname: "{{ ad_surname }}"
         company: "{{ ad_company }}"
         password: "{{ ad_userpwd }}"
         state: "{{ ad_user_state }}"
         groups: "{{ ad_groups }}"
         street: "{{ ad_street }}"
         city: "{{ ad_city }}"
         state_province: "{{ ad_state }}"
         postal_code: "{{ ad_postal_code }}"
         country: "{{ ad_country }}"
