---
- name: Register Linux RHEL Systems to Spacewalk
  hosts: all
  
  tasks:
    - name: Ensure {{ inventory_hostname }} is registered on Spacewalk system
      shell: |
        wget --no-proxy http://ecarbsul0770h01.dc.admin.europcar.vwfs-ad/pub/RHN-ORG-TRUSTED-SSL-CERT 
        rhnreg_ks --serverUrl=https://ecarbsul0770h01.dc.admin.europcar.vwfs-ad/XMLRPC --sslCACert=/usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT --activationkey=2-uat-crit-rhel7-x86_64-std
      args:
        chdir: /usr/share/rhn/
