---
  - name: Ensure IIS Web Sevrer is installed
    win_feature:
      name: Web-Server
      state: present
  
  - name: Deploy default iisstart.htm
    template:
      src: iisstart.j2
      dest: c:\inetpub\wwwroot\iisstart.htm
